-- colorscheme autogenerated with base16

-- custom base colorscheme system
require("colorscheme.colorscheme_colors").setup(require("systemcolors"))

-- main
require("core")
require("options")
require("keymaps")
require("systemspecific")

-- plugins and settings
require("plugins")
require("pluginconf.nvim-autopairs")
require("pluginconf.alphaconf")
require("pluginconf.bufferline")
require("pluginconf.latex")
require("pluginconf.lspsaga")
require("pluginconf.luasnip")
require("pluginconf.telescope")
require("pluginconf.treesitter")
require("pluginconf.autoformat")
require("pluginconf.cmp")
-- require("pluginconf.lsp")
require("pluginconf.lualine")
require("pluginconf.nvim-tree")
require("pluginconf.toggleterm")
require("pluginconf.null-ls")
require("pluginconf.gitsigns")
require("pluginconf.lsp-signature")
require("pluginconf.lspsaga")
require("pluginconf.vimwiki")
require("pluginconf.mason")

-- require("other.test")

-- sourcing color scheme adjustments
require("colorscheme.colorscheme_colors").setup(require("systemcolors"))
require("commands")

-- needs fixing
require("Comment").setup()

-- local dap = require('dap')
-- dap.adapters.unity = {
--     type = 'executable',
--     command = '/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono',
--     args = {'/Users/unalozyurt/.vscode/extensions/unity.unity-debug-3.0.2/bin/UnityDebug.exe'}
--   }
--   
--   dap.configurations.cs = {
--     {
--     type = 'unity',
--     request = 'attach',
--     name = 'Unity Editor',
--     program = function()
--       return 
--     end,
--     }
--   }

-- vim.opt.scroll="10"
