-- colorscheme autogenerated with base16

-- custom base colorscheme system
-- require("colorscheme.colorscheme_colors").setup(require("systemcolors"))

-- main
require("core")
require("options")
require("keymaps")
require("systemspecific")

-- plugins and settings
require("plugins")
require("impatient")
require("pluginconf.nvim-autopairs")
require("pluginconf.alphaconf")
require("pluginconf.bufferline")
require("pluginconf.latex")
require("pluginconf.lspsaga")
require("pluginconf.luasnip")
require("pluginconf.telescope")
require("pluginconf.treesitter")
require("pluginconf.autoformat")
require("pluginconf.cmp")
-- require("pluginconf.lsp")
require("pluginconf.lualine")
require("pluginconf.nvim-tree")
require("pluginconf.toggleterm")
require("pluginconf.null-ls")
require("pluginconf.gitsigns")
require("pluginconf.lsp-signature")
require("pluginconf.lspsaga")
require("pluginconf.windows")
require("pluginconf.reach")
require("pluginconf.vimwiki")
require("pluginconf.dap")
require("pluginconf.mason")

-- require("other.test")

-- sourcing color scheme adjustments
require("colorscheme.colorscheme_colors").setup(require("systemcolors"))
require("commands")

-- vim.opt.scroll="10"
